Part4
KottV/PFMCPP_Project3 pull request #4
Opened 2021-03-23 11:25 UTC by KottV

2021-03-23 23:01 UTC, matkatmusic requested changes
You only changed one class to conform with this instruction:
```
1) initialize some of your member variables either in-class or in the Constructor 
member initializer list.

 2) make some of your member functions use those initialized member variables 
via std::cout statements.

```
Please revise all of your classes, including the nested ones, to demonstrate to me that you understand these concepts.

2021-03-23 23:01 UTC, matkatmusic commented on main.cpp
> +        std::cout<<"outV:"<<outVolt<<std::endl;
Improve the readability by adding spaces around `<<`
- [ ] revise

2021-03-23 23:01 UTC, matkatmusic commented on main.cpp
> +
From project3.3:
```
 3) Instantiate 1 or 2 instances of each of your user-defined types in the main() function

 4) call some of your UDT's amended member functions in main().
 
 5) add some std::cout statements in main() that print out your UDT's member 
variable values or values returned from your UDT member functions (if they return values)
 ```
Your `main()` is lacking a lot of code.  
Instantiate your objects and call their member functions to make sure your code works.
- [ ] revise

2021-03-25 11:07 UTC, KottV commented
I pushed the updated code. It has more outputs of UDT members and all constructors are in-class (except "Cat").
Also I played with std::cout as you can see. That's way I'd like to know what is good and what is not so.

2021-03-26 09:33 UTC, matkatmusic approved these changes

2021-03-26 09:33 UTC, merged